### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by cgendreau** [dina-web-nrm/dina-collections-ui#90]
Why this project is not licensed as MIT?

**Comment by mikkohei13** [comment]
The (draft) guidelines tell to use "a well-known and widely used open source license", but leave the details open: https://github.com/DINA-Web/guidelines/blob/master/DINA-Web-Licensing-Guidelines.md

I don't know the process behind creating this guideline. Affero GPL has been favoured for making possible third-party contributions also open-source. Is there a reason to prefer MIT instead?

**Comment by cgendreau** [comment]
I don't known why the document offers a choice for new  projects. As it says, MIT is "simple and permissive". AGPL contains more restrictions so for the DINA project I would suggest MIT licenses unless it's impossible (e.g. the project includes modified source code of a library licensed as AGPL).

**Comment by mikkohei13** [comment]
Discussion on license guidelines on more detailed level (exactly what license, what are the implications, what is compulsory) should involve others also, so talking about this at the Berlin meeting could be a good idea.

**Comment by cgendreau** [comment]
It has already been discussed, it's in the guideline and it doesn't really create a problem.
Closing
